# Numpy - Numerical Python

In [1]:
# The convention is to import it as np
import numpy as np

In [2]:
np.__version__

'1.21.0'

Numpy arrays are similar to lists, except they only store one data type.
This makes them faster.

In [3]:
# We can create a numpy array from a list
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
# If we have a float in a numpy array, the entire array becomes floats
my_array_2 = np.array([1.1, 2, 3, 4, 5])
my_array_2

array([1.1, 2. , 3. , 4. , 5. ])

In [6]:
my_array.dtype

dtype('int64')

In [7]:
my_array_2.dtype

dtype('float64')

In [8]:
my_array_3 = np.array([1, 2, 3, 4, 5], dtype = 'float64')
my_array_3

array([1., 2., 3., 4., 5.])

In [9]:
my_array_3.dtype

dtype('float64')

In [10]:
# There are many different ways of creating an array. 
# Here are some common ones
np.arange(0, 10) # (start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 11) # 11 values evenly spaced between 0 and 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.ones((3, 3), dtype = np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros((2, 3, 4), dtype = np.int64)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [14]:
# We can create an array of random integers
np.random.randint(0, 50, (2, 4, 5))

array([[[46, 33,  6, 35, 43],
        [23,  6, 29,  6,  1],
        [30, 46, 49, 28, 17],
        [22, 22, 22, 40, 11]],

       [[ 1, 13,  2, 22, 40],
        [36, 12,  3, 34, 11],
        [26, 19, 21, 39, 19],
        [35, 45,  8, 43, 22]]])

### Array Arithmetic

In [15]:
my_arr = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8]
])
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
my_arr.shape

(2, 4)

In [17]:
my_arr + my_arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [18]:
my_arr * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [19]:
my_arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [20]:
my_arr < 3

array([[ True,  True, False, False],
       [False, False, False, False]])

### Array indexing

In [21]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
my_arr[1]

array([5, 6, 7, 8])

In [23]:
my_arr[1][2]

7

In [24]:
my_arr[1, 2]

7

In [25]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_slice = arr2[3:7]
my_slice

array([3, 4, 5, 6])

In [27]:
my_slice[2] = 88

In [28]:
arr2

array([ 0,  1,  2,  3,  4, 88,  6,  7,  8,  9])

In [29]:
# Indexing is [start:stop:step]
arr2[:4]

array([0, 1, 2, 3])

In [30]:
arr2[4:]

array([ 4, 88,  6,  7,  8,  9])

In [31]:
arr2[3:8]

array([ 3,  4, 88,  6,  7])

In [32]:
arr2[::2]

array([0, 2, 4, 6, 8])

In [33]:
arr3 = np.random.randint(0, 50, (5, 5))
arr3

array([[41, 17, 39, 49, 34],
       [31, 40, 29, 18, 46],
       [41,  6,  3, 19, 31],
       [36, 24,  4, 40, 36],
       [11, 46, 12, 25, 19]])

In [34]:
arr3[:4, 1:4]

array([[17, 39, 49],
       [40, 29, 18],
       [ 6,  3, 19],
       [24,  4, 40]])

In [35]:
arr3[:, ::2]

array([[41, 39, 34],
       [31, 29, 46],
       [41,  3, 31],
       [36,  4, 36],
       [11, 12, 19]])

In [36]:
arr3[:, 0] # First column

array([41, 31, 41, 36, 11])

In [37]:
arr3[0, :] # First row

array([41, 17, 39, 49, 34])

In [38]:
# Returns an array boolean values (True if the original value was greater than 22, False otherwise)
arr3 > 22

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False, False, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True, False]])

In [39]:
# We can create a mask to select only those values that are true
arr3[arr3 > 22]

array([41, 39, 49, 34, 31, 40, 29, 46, 41, 31, 36, 24, 40, 36, 46, 25])

In [40]:
# Traspose the array
arr3.T

array([[41, 31, 41, 36, 11],
       [17, 40,  6, 24, 46],
       [39, 29,  3,  4, 12],
       [49, 18, 19, 40, 25],
       [34, 46, 31, 36, 19]])

In [41]:
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])

In [42]:
np.concatenate([arr4, arr5])

array([1, 2, 3, 4, 5, 6])

In [43]:
arr6 = np.array([
  [7, 8, 9],
  [10, 11, 12]
])

In [44]:
# Concatenate arrays. If no axis is specified, axis = 0 is used by default).
# This means that the resulting array will grow along that axis (vertically stacked).
np.concatenate([arr6, arr6])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
# axis = 1 will add columns
np.concatenate([arr6, arr6], axis = 1)

array([[ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [46]:
# Vertical stack
np.vstack([arr4, arr6])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
# Horizontal stacking
arr7 = np.array([[70], [80]])
np.hstack([arr6, arr7])

array([[ 7,  8,  9, 70],
       [10, 11, 12, 80]])

In [48]:
# Find the min of each column
print(arr3)
arr3.min(axis = 0)

[[41 17 39 49 34]
 [31 40 29 18 46]
 [41  6  3 19 31]
 [36 24  4 40 36]
 [11 46 12 25 19]]


array([11,  6,  3, 18, 19])

In [49]:
# Min value of each row
print(arr3)
arr3.min(axis = 1)

[[41 17 39 49 34]
 [31 40 29 18 46]
 [41  6  3 19 31]
 [36 24  4 40 36]
 [11 46 12 25 19]]


array([17, 18,  3,  4, 11])

In [50]:
# Find the min value on all axis
print(arr3)
arr3.min()

[[41 17 39 49 34]
 [31 40 29 18 46]
 [41  6  3 19 31]
 [36 24  4 40 36]
 [11 46 12 25 19]]


3

In [51]:
# We can do the same with mean
arr3.mean()

27.88

In [52]:
arr3.mean(axis = 0)

array([32. , 26.6, 17.4, 30.2, 33.2])

In [53]:
arr3.mean(axis = 1)

array([36. , 32.8, 20. , 28. , 22.6])

In [54]:
np.sqrt(arr3)

array([[6.40312424, 4.12310563, 6.244998  , 7.        , 5.83095189],
       [5.56776436, 6.32455532, 5.38516481, 4.24264069, 6.78232998],
       [6.40312424, 2.44948974, 1.73205081, 4.35889894, 5.56776436],
       [6.        , 4.89897949, 2.        , 6.32455532, 6.        ],
       [3.31662479, 6.78232998, 3.46410162, 5.        , 4.35889894]])