### Numpy - Numerical Python

In [1]:
# The convention is to import it as np
import numpy as np

In [2]:
np.__version__

'1.21.0'

Numpy arrays are similar to lists, except they only store one data type.
This makes them faster.

In [3]:
# We can create a numpy array from a list
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
# If we have a float in a numpy array, the entire array becomes floats
my_array_2 = np.array([1.1, 2, 3, 4, 5])
my_array_2

array([1.1, 2. , 3. , 4. , 5. ])

In [6]:
my_array.dtype

dtype('int64')

In [7]:
my_array_2.dtype

dtype('float64')

In [8]:
my_array_3 = np.array([1, 2, 3, 4, 5], dtype = 'float64')
my_array_3

array([1., 2., 3., 4., 5.])

In [9]:
my_array_3.dtype

dtype('float64')

In [10]:
# There are many different ways of creating an array. 
# Here are some common ones
np.arange(0, 10) # (start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 11) # 11 values evenly spaced between 0 and 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.ones((3, 3), dtype = np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros((2, 3, 4), dtype = np.int64)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [14]:
# We can create an array of random integers
np.random.randint(0, 50, (2, 4, 5))

array([[[42, 26,  9, 23,  7],
        [40, 18,  3, 19, 17],
        [28, 35,  5,  0, 12],
        [29, 18,  3, 18, 45]],

       [[19, 18, 25, 13, 27],
        [13, 38, 35, 41, 34],
        [47, 47, 18,  3, 48],
        [18, 18, 18, 36, 27]]])

### Array Arithmetic

In [16]:
my_arr = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8]
])
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
my_arr.shape

(2, 4)

In [27]:
my_arr + my_arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [28]:
my_arr * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [29]:
my_arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [30]:
my_arr < 3

array([[ True,  True, False, False],
       [False, False, False, False]])

### Array indexing

In [31]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
my_arr[1]

array([5, 6, 7, 8])

In [33]:
my_arr[1][2]

7

In [34]:
my_arr[1, 2]

7

In [36]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
my_slice = arr2[3:7]
my_slice

array([3, 4, 5, 6])

In [38]:
my_slice[2] = 88

In [39]:
arr2

array([ 0,  1,  2,  3,  4, 88,  6,  7,  8,  9])

In [40]:
# Indexing is [start:stop:step]
arr2[:4]

array([0, 1, 2, 3])

In [41]:
arr2[4:]

array([ 4, 88,  6,  7,  8,  9])

In [42]:
arr2[3:8]

array([ 3,  4, 88,  6,  7])

In [43]:
arr2[::2]

array([0, 2, 4, 6, 8])

In [44]:
arr3 = np.random.randint(0, 50, (5, 5))
arr3

array([[ 7, 19, 32, 17,  1],
       [ 9, 46,  9,  2,  7],
       [21, 28, 26, 11,  6],
       [ 7, 48,  8,  9,  9],
       [ 5, 26, 28,  7, 11]])

In [45]:
arr3[:4, 1:4]

array([[19, 32, 17],
       [46,  9,  2],
       [28, 26, 11],
       [48,  8,  9]])

In [46]:
arr3[:, ::2]

array([[ 7, 32,  1],
       [ 9,  9,  7],
       [21, 26,  6],
       [ 7,  8,  9],
       [ 5, 28, 11]])

In [47]:
arr3[:, 0] # First column

array([ 7,  9, 21,  7,  5])

In [48]:
arr3[0, :] # First row

array([ 7, 19, 32, 17,  1])

In [49]:
arr3 > 22

array([[False, False,  True, False, False],
       [False,  True, False, False, False],
       [False,  True,  True, False, False],
       [False,  True, False, False, False],
       [False,  True,  True, False, False]])

In [54]:
# We can create a mask to select only those values that are true
arr3[arr3 > 22]

array([32, 46, 28, 26, 48, 26, 28])

In [55]:
arr3.T

array([[ 7,  9, 21,  7,  5],
       [19, 46, 28, 48, 26],
       [32,  9, 26,  8, 28],
       [17,  2, 11,  9,  7],
       [ 1,  7,  6,  9, 11]])

In [56]:
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])

In [57]:
np.concatenate([arr4, arr5])

array([1, 2, 3, 4, 5, 6])

In [58]:
arr6 = np.array([
  [7, 8, 9],
  [10, 11, 12]
])

In [59]:
np.concatenate([arr6, arr6])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.concatenate([arr6, arr6], axis = 1)

array([[ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [61]:
np.vstack([arr4, arr6])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
arr7 = np.array([[70], [80]])
np.hstack([arr6, arr7])

array([[ 7,  8,  9, 70],
       [10, 11, 12, 80]])

In [67]:
arr3.min(axis = 0)

array([ 5, 19,  8,  2,  1])

In [66]:
arr3.min(axis = 1)

array([1, 2, 6, 7, 5])

In [68]:
arr3.min()

1

In [69]:
arr3.mean()

15.96

In [71]:
arr3.mean(axis = 0)

array([ 9.8, 33.4, 20.6,  9.2,  6.8])

In [72]:
arr3.mean(axis = 1)

array([15.2, 14.6, 18.4, 16.2, 15.4])

In [73]:
np.sqrt(arr3)

array([[2.64575131, 4.35889894, 5.65685425, 4.12310563, 1.        ],
       [3.        , 6.78232998, 3.        , 1.41421356, 2.64575131],
       [4.58257569, 5.29150262, 5.09901951, 3.31662479, 2.44948974],
       [2.64575131, 6.92820323, 2.82842712, 3.        , 3.        ],
       [2.23606798, 5.09901951, 5.29150262, 2.64575131, 3.31662479]])